### ISSUE TITLE
Have git ignore a developer API key by default

### ISSUE THREAD

**Issue by jessmartin** [croquet/greenlight-core#2]
Let's make it really easy for developers to use their own [Croquet API Key](https://croquet.io/keys/).

- Check in a file called `apiKey.js.example`
- Make one of the install steps `cp apiKey.js.example apiKey.js`
- Add `apiKey.js` to `.gitignore`

That way, developers add their API key to an ignored file that's not checked in by default.

Could also have `server.js` intelligently fail when there is no `apiKey.js` file.

**Comment by yoshikiohshima** [comment]
closed
